# Generated by Django 2.1.5 on 2019-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', 'First semester'), ('2', 'Second semester'), ('3', 'Third semester'), ('4', 'Fourth semester')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='semester',
            field=models.CharField(choices=[('1', 'First semester'), ('2', 'Second semester'), ('3', 'Third semester'), ('4', 'Fourth semester')], default='1', max_length=1),
        ),
    ]
