# Generated by Django 2.1.5 on 2019-05-18 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20190326_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('assign_text', models.TextField(max_length=800)),
                ('assign_file', models.FileField(upload_to='assignments/%Y/%m/%d/')),
                ('staff_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Lecturer')),
                ('unit_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Unit')),
            ],
        ),
    ]
