# Generated by Django 2.1.5 on 2019-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='unit_code',
            field=models.CharField(max_length=200),
        ),
    ]
