# Generated by Django 2.1.5 on 2019-06-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20190519_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_file', models.FileField(upload_to='assignments/%Y/%m/%d/')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('adm_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Student')),
                ('assign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
            ],
        ),
    ]
