# Generated by Django 2.1.5 on 2019-06-21 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(auto_now_add=True)),
                ('material_file', models.FileField(upload_to='materials/%Y/%m/%d/')),
                ('description', models.TextField(max_length=800)),
                ('staff_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Lecturer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Unit')),
            ],
        ),
    ]
