# Generated by Django 2.1.5 on 2019-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unit',
        ),
        migrations.AddField(
            model_name='material',
            name='unit_code',
            field=models.CharField(default='com', max_length=200),
            preserve_default=False,
        ),
    ]
